# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastStabbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stabbed', models.DateField(default=datetime.date.today)),
                ('article_url', models.URLField()),
                ('submitted_by', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
