# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 14:46
from __future__ import unicode_literals

import datetime
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('days', '0002_auto_20170504_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastShooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateField(default=datetime.date.today)),
                ('article_url', models.URLField()),
                ('submitted_by', models.CharField(blank=True, max_length=64, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Last Shootings',
                'verbose_name': 'Last Shooting',
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='laststabbing',
            options={'verbose_name': 'Last Stabbing', 'verbose_name_plural': 'Last Stabbings'},
        ),
        migrations.RenameField(
            model_name='laststabbing',
            old_name='date_stabbed',
            new_name='date_event',
        ),
    ]
