# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0003_add_lastshooting'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastshooting',
            name='datetime_event',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='datetime_event',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
