# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0006_delete_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastshooting',
            name='site',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE,
                to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='laststabbing',
            name='site',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE,
                to='sites.Site'),
        ),    
    ]
