# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 03:35
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0007_set_default_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lastshooting',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='laststabbing',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='city',
            field=models.CharField(default='Ottawa', max_length=64),
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='country',
            field=models.CharField(default='Canada', max_length=64),
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='is_fatal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='is_pending_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=45.4215, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='lng',
            field=models.DecimalField(decimal_places=9, default=-75.6972, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='number',
            field=models.IntegerField(blank=True, default=0, help_text='The number/block of the address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='province',
            field=models.CharField(default='Ontario', max_length=32),
        ),
        migrations.AddField(
            model_name='lastshooting',
            name='street',
            field=models.CharField(default='Wellington St.', help_text='The street name ONLY (no numbers)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='city',
            field=models.CharField(default='Ottawa', max_length=64),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='country',
            field=models.CharField(default='Canada', max_length=64),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='is_fatal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='is_pending_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=45.4215, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='lng',
            field=models.DecimalField(decimal_places=9, default=-75.6972, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='number',
            field=models.IntegerField(blank=True, default=1, help_text='The number/block of the address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='province',
            field=models.CharField(default='Ontario', max_length=32),
        ),
        migrations.AddField(
            model_name='laststabbing',
            name='street',
            field=models.CharField(default='Wellington St.', help_text='The street name ONLY (no numbers)', max_length=255),
            preserve_default=False,
        ),
    ]
